binlee0903/se13_team_project

.github/workflows/gradle.yml

우선은 main 브랜치에 푸시랑 풀 리퀘스트를 보냈을 때만 감지하도록 했습니다.

GIthub Actions로 자동 빌드/테스트 추가

---

app/src/main/java/org/se13/game/GameStatus.java
app/src/main/java/org/se13/game/block/Block.java
app/src/main/java/org/se13/game/block/BlockPosition.java
app/src/main/java/org/se13/game/block/CurrentBlock.java
app/src/main/java/org/se13/game/block/IBlock.java
app/src/main/java/org/se13/game/block/JBlock.java
app/src/main/java/org/se13/game/block/LBlock.java
app/src/main/java/org/se13/game/block/OBlock.java
app/src/main/java/org/se13/game/block/SBlock.java
app/src/main/java/org/se13/game/block/TBlock.java
app/src/main/java/org/se13/game/block/ZBlock.java
app/src/main/java/org/se13/game/config/GameConfig.java
app/src/main/java/org/se13/game/grid/TetrisGrid.java
app/src/main/java/org/se13/game/rule/BlockQueue.java

issue: #12 
테트리스가 떨어지는 로직은 JavaFX의 구조를 공부하고 메인 쓰레드나 이벤트 큐와 연동이 필요한 작업이라
JavaFX 를 공부 후 이어서 작업하겠습니다.

테트리스 구현에 필요한 주요 로직들 구현입니다.

---

app/build.gradle.kts
app/src/main/java/module-info.java
app/src/main/java/org/se13/sqlite/config/ConfigRepository.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java
app/src/main/java/org/se13/sqlite/ranking/RankingRepository.java
app/src/main/java/org/se13/sqlite/ranking/RankingRepositoryImpl.java

Issue: #7, #15 
- build.gradle에 sqlite와 json의 implementation 추가
- module-info에 java.sql과 org.json 추가
- sqlite directory에 ConfigRepository 인터페이스 생성 및 ConfigRepositoryImpl 구현
- sqlite directory에 RankingRepository의 인터페이스 생성 및 RankingRepositoryImpl 구현

feat: ConfigRepository & RankingRepository 추가 및 구현

---

app/src/main/java/org/se13/sqlite/ranking/RankingRepository.java
app/src/main/java/org/se13/sqlite/ranking/RankingRepositoryImpl.java
app/src/main/java/org/se13/view/ranking/Ranking.java
app/src/main/java/org/se13/view/ranking/RankingScreenController.java
app/src/main/resources/org/se13/RankingScreen.fxml

Issue: #15, #21 
- RankingRepository에 Ranking 테이블을 생성하는 createNewTableRanking 함수가 빠져있던 문제 수정
- Ranking 테이블의 points컬럼 score로 컬럼 이름 변경
- 랭킹테이블에 표현되는 값들의 클래스 [Ranking.java](Ranking.java)
- 뷰에 랭킹테이블 추가 [RankingScreen.fxml](RankingScreen.fxml)
- 랭킹 컨트롤러 구현 [RankingScreenController.java](RankingScreenController.java)

RankingRepository 수정 및 Ranking의 View & Controller 구현

---

app/src/main/java/org/se13/sqlite/config/ConfigRepository.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java

Issue: #7 
- keyRotate를 keyRotateLeft와 keyRotateRight로 변경
insertDefaultConfig에 기본값을 임의로 설정해 두었으니 확인 후 변경 부탁드립니다.
```java
@Override
public void insertDefaultConfig(int id) {
JSONObject json = new JSONObject();
json.put("mode", "default");
json.put("gridWidth", 10);
json.put("gridHeight", 22);
json.put("keyLeft", 75);
json.put("keyRight", 77);
json.put("keyDown", 80);
json.put("keyRotateLeft", 120);
json.put("keyRotateRight", 121);
json.put("keyPause", 32);
String sql = "INSERT INTO config (id, settings) VALUES(?,?)";
try (Connection conn = this.connect();
PreparedStatement pstmt = conn.prepareStatement(sql)) {
pstmt.setInt(1, id);
pstmt.setString(2, json.toString());
pstmt.executeUpdate();
} catch (SQLException e) {
System.out.println(e.getMessage());
}
}
```

chore: ConfigRepository 역방향 회전 추가

---

app/src/main/java/org/se13/StackNavGraph.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java
app/src/main/java/org/se13/view/setting/SettingScreenController.java
app/src/main/resources/org/se13/SettingScreen.fxml

#30 
현재까지 해상도와 색맹 모드를 DB에 저장하기 위해 기본값들을 설정했습니다.
해상도는 300 * 400, 600 * 800, 1920 * 1080 세 가지 중 선택 가능하게 하고,
색맹 모드는 Nothing, 적록색맹, 황청색맹 세 가지 중 선택 가능하게 해야 합니다.
두 가지 모두 ChoiceBox로 하여 Controller에서는 getValue 함수를 통해 유저가 선택한 값을 가져옵니다.

Setting 현재까지 작업 사항: 해상도, 색맹모드

---

app/src/main/java/org/se13/view/setting/SettingScreenController.java
app/src/main/resources/org/se13/SettingScreen.fxml
app/src/main/resources/org/se13/style.css

#30 
Setting 화면에 key setting 버튼을 만들었습니다. 각각의 버튼의 작동은 SettingController의 keySaveButtonAction 메서드를 통합니다. 메서드에 대한 자세한 구현은 다음 pr에 올릴 예정입니다.
픽셀 계산을 해보니까 스크롤 할 필요가 없어서 수정하지는 않았습니다.

feat:Setting 화면에 key setting 버튼 생성

---

.gitignore
app/build.gradle.kts
app/src/main/java/module-info.java
app/src/main/java/org/se13/NavGraph.java
app/src/main/java/org/se13/SE13Application.java
app/src/main/java/org/se13/StackNavGraph.java
app/src/main/java/org/se13/view/base/BaseController.java
app/src/main/java/org/se13/view/lifecycle/Lifecycle.java
app/src/main/java/org/se13/view/ranking/RankingScreenController.java
app/src/main/java/org/se13/view/setting/SettingScreenController.java
app/src/main/java/org/se13/view/start/StartScreenController.java
app/src/main/java/org/se13/view/tetris/TetrisScreenController.java
app/src/test/java/org/se13/StackNavGraphTest.java

issue: #34 
initalize 함수는 마찬가지로 Consumer<T> 보다 먼저 실행됩니다.
화면이 보이기 전에 onCreate 메서드가 실행되고, 화면이 보이고 나서 onStart가 실행됩니다.

라이프사이클 구현입니다.

---

app/src/main/java/org/se13/sqlite/config/ConfigRepository.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java

- insertDefaultConfig
- updateConfig
- getConfig 
위 세 함수에 keyDrop, keyExit 추가

feat: Drop, Exit 키 추가

---

app/src/main/java/org/se13/sqlite/ranking/RankingRepository.java
app/src/main/java/org/se13/sqlite/ranking/RankingRepositoryImpl.java
app/src/main/java/org/se13/view/ranking/Ranking.java
app/src/main/java/org/se13/view/ranking/RankingScreenController.java
app/src/main/resources/org/se13/RankingScreen.fxml

Issues: #39, #40
Ranking
- 최근 값 판별을 위해 id 항목 추가  
RankingRepository
- isItem, diff 추가  
RankingRepositoryImpl
- ranking table에 isItem, diff 컬럼 추가
- insertRanking에 isItem, diff 추가
- getRanking에 id, isItem, diff 추가
- 테스트 코드 삭제
RankingScreen.fxml
- isItem, diff 추가
- tetrisButton, homeButton 위치 변경
RankingScreenController
- isItem, diff 추가
- LifeCycle 적용
- setArguments 적용
- 최근 입력 값 highlighting

feat: 최근 값 highlighting 및 isItem, diff 추가

---

app/src/main/java/org/se13/StackNavGraph.java
app/src/main/java/org/se13/game/tetris/DefaultTetrisGame.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java
app/src/main/java/org/se13/view/setting/SettingScreenController.java

프로그램 시작시 db에서 화면크기를 가져오도록 했습니다.

feature/resize window #43 #32

---

app/build.gradle.kts
app/src/main/java/org/se13/game/rule/BlockQueue.java
app/src/main/java/org/se13/game/rule/BlockWeight.java
app/src/main/java/org/se13/game/rule/GameLevel.java
app/src/main/java/org/se13/game/tetris/DefaultTetrisGame.java
app/src/test/java/org/se13/game/rule/BlockQueueTest.java

feat: 쉬움 난이도에선 I형 블록이 20% 더 자주 등장, 어려움에선 20% 덜 등장하는 기능 추가

---

app/src/main/java/org/se13/view/tetris/GameOverScreenController.java
app/src/main/resources/org/se13/GameOverScreen.fxml

- GameOver에서 닉네임 입력 과정 삭제
- navController.navigate을 이용해 화면 및 값 이동

fix: GameOver2RankingScreen 값 이동 수정

---

app/src/main/java/org/se13/view/ranking/RankingScreenController.java
app/src/test/java/org/se13/sqlite/ranking/RankingRepositoryImplTest.java
app/src/test/java/org/se13/view/ranking/RankingScreenControllerTest.java

- 테스트를 위해 RankingScreenController에 getter 추가
- connect를 제외한 RankingRepository의 모든 메서드 테스트
- RankingScreen의 setArgumemts 테스트
RankingRepository의 거의 모든 메서드에 대한 테스트 코드는 작성할 수 있었지만 최대한 많은 라인을 커버하려고 노력하였음에도 불구하고 view부분은 setArguments를 제외하곤 작성할 수 없었습니다. 
혹시나 view부분에 대한 테스트 코드 작성 방법에 대해 아시는 분은 조언 해주시면 감사하겠습니다...

test: RankingRepository & RankingScreen Test Code

---

app/src/main/java/org/se13/SE13Application.java
app/src/main/java/org/se13/StackNavGraph.java
app/src/test/java/org/se13/StackNavGraphTest.java
app/src/test/java/org/se13/sqlite/config/FakeConfigRepository.java
app/src/test/java/org/se13/view/nav/ScreenTest.java

1. 초기 NavGraph는 아무 Screen도 포함하지 않음
2. Screen은 .fxml 확장자만 지원

테스트 할 수 있는 곳들 조금 추가했습니다.

---

app/src/main/java/org/se13/NavGraph.java
app/src/main/java/org/se13/StackNavGraph.java
app/src/main/java/org/se13/game/tetris/DefaultTetrisGame.java
app/src/main/java/org/se13/sqlite/config/ConfigRepository.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java
app/src/main/java/org/se13/view/setting/SettingScreenController.java

스크린 사이즈 변경 기능 추가

---

app/src/main/java/org/se13/game/block/Block.java
app/src/main/java/org/se13/game/block/CellID.java
app/src/main/java/org/se13/game/grid/TetrisGrid.java
app/src/main/java/org/se13/game/rule/BlockQueue.java
app/src/main/java/org/se13/game/tetris/DefaultTetrisGame.java

Issue: #63 
```java
// Block.java Line 79
WeightItemBlock(new int[][][]{
{{1, 0}, {1, 1}, {1, 2}, {1, 3}},
}, new int[]{0, 3}, CellID.WEIGHT_ITEM_ID, new BlockColor(
Color.rgb(255, 255, 255),
Color.rgb(255, 255, 255),
Color.rgb(255, 255, 255)));
```
```java
// CellID.java Line 15
WEIGHT_ITEM_ID,
```
```java
// BlockQueue.java Line 57
//        blocks.put(Block.WeightItemBlock, BlockWeight.Normal);
```
```java
// DefaultTetrisGame.java 
// Line 181
public TetrisGrid getTetrisGrid() {
return this.tetrisGameGrid;
}
// Line 359
// WeightBlock이 떨어졌을 때, 해당 열을 지워줌
if (isBlockPlaced == true && currentBlock.getId() == Block.WeightItemBlock.cellId) {
int clearedColIndex = currentBlock.getPosition().getColIndex();
tetrisGameGrid.clearWeightCol(clearedColIndex);
}
// Line 408
if (nextBlock.getId() == …
```

feat: 무게추 아이템 추가

---

app/src/main/java/org/se13/game/tetris/DefaultTetrisGame.java
app/src/main/java/org/se13/game/timer/FeverModeTimer.java
app/src/test/java/org/se13/game/timer/FeverModeTimerTest.java

기본 20초 동안 피버 모드가 활성화됩니다.
일시정지 시 피버모드 시간은 흘러가지 않습니다.

피버모드 구현 추가입니다.

---

app/src/main/java/org/se13/NavGraph.java
app/src/main/java/org/se13/SE13Application.java
app/src/main/java/org/se13/StackNavGraph.java
app/src/main/java/org/se13/game/tetris/DefaultTetrisGame.java
app/src/main/java/org/se13/view/difficulty/LevelSelectScreenController.java
app/src/main/java/org/se13/view/nav/AppScreen.java
app/src/main/java/org/se13/view/ranking/RankingScreenController.java
app/src/main/java/org/se13/view/start/StartScreenController.java
app/src/main/java/org/se13/view/tetris/GameOverScreenController.java
app/src/test/java/org/se13/view/nav/AppScreenTest.java

#32 
화면 크기를 설정 화면에서 변경했을 때, 화면이 적절하게 사용자에게 보여질 수 있도록 나타나는 화면의 위치를 임의로 설정했습니다. 작은 화면의 경우에는 화면 중앙에, 1920*1080 경우에는 화면에 꽉 차도록 조정을 했습니다. 
추후에 전체 화면 모드가 필요할 수도 있을 것 같은데, 이 부분은 scene 함수에서 처리할 수 있는 것 같아서 나중에 해보겠습니다.

화면 크기 설정 변경 시 변경 사항 조정

---

app/src/main/java/org/se13/game/rule/BlockQueue.java
app/src/test/java/org/se13/game/rule/BlockQueueTest.java

요구사항에선 1천번 이상 선택을 반복하라고 했는데 1만번까지는 테스트 실패하는 경우가 간혹 있어서
10만번 반복으로 테스트 코드 작성했습니다.

블록 확률 오차범위 5% 이내에서 유효한지 테스트 추가

---

app/src/main/java/org/se13/game/tetris/DefaultTetrisGame.java
app/src/test/java/org/se13/game/tetris/TetrisGameTest.java

아까 아이템 테스트하려고 올렸던 코드에서 오류가 있었네요
빌드 파일은 제가 변경해두겠습니다.

아이템이 등장하지 않는 버그 수정

---

app/src/main/resources/org/se13/StartScreen.fxml

오늘 발견한 게임 이름이 제대로 표시되지 않는 문제를 해결했습니다.

fix: 게임이름이 제대로 표시되지 않던 문제 해결

---

app/src/main/java/module-info.java
app/src/main/java/org/se13/sqlite/ranking/Ranking.java
app/src/main/java/org/se13/sqlite/ranking/RankingRepository.java
app/src/main/java/org/se13/sqlite/ranking/RankingRepositoryImpl.java
app/src/main/java/org/se13/view/ranking/RankingProperty.java
app/src/main/java/org/se13/view/ranking/RankingScreenController.java
app/src/test/java/org/se13/sqlite/ranking/RankingRepositoryImplTest.java
app/src/test/java/org/se13/sqlite/ranking/RankingTest.java

Issue: #86 
- `RankingRepositoryImpl`의 인스턴스를 클래스의 필드로 선언하고 초기화하였습니다.
```java
public RankingScreenController() {
this.rankingRepository = new RankingRepositoryImpl();
}
// ...
private final RankingRepository rankingRepository;
```
- 랭킹 데이터를 가져오는 부분을 `loadRankingData` 메소드로 분리하였습니다.
```java
private List<Map<String, Object>> loadRankingData() {
return rankingRepository.getRankingList();
}
```
- `showNicknameInputUI`와 `getLastRankingScore`에서 `loadRankingData` 메소드를 사용합니다.
```java
private void showNicknameInputUI() {
// ...
rankingRepository.insertRanking(nickname, score, isItem, diff);
List<Map<String, Object>> rankingData = loadRankingData();
// ...
}
public void loadRanking() {
List<Map<String, Object>> rankingData = loadRankingData();
// ...
}
```
- 노션 문서의 코딩 스탠다드에 맞추어 순서를 개선하였습니다.

refactor: RankingScreenController refactoring

---

app/src/main/java/org/se13/SE13Application.java
app/src/main/java/org/se13/game/block/Block.java
app/src/main/java/org/se13/game/config/Config.java
app/src/main/java/org/se13/sqlite/config/ConfigRepository.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java
app/src/main/java/org/se13/view/setting/SettingScreenController.java
app/src/test/java/org/se13/sqlite/config/ConfigRepositoryImplTest.java
app/src/test/java/org/se13/view/controller/ControllerTest.java

#59 issue 1,2,3번을 처리했고, 4번은 진행 중에 있습니다.
추가로, 초기화 버튼을 눌렀을 때 저장 버튼을 누르지 않아도 디폴트 값이 저장이 되도록 수정했습니다.

refactor: config issue 1,2,3 + 초기화 버튼 로직 수정

---

app/src/main/java/org/se13/view/setting/SettingScreenController.java
app/src/main/resources/org/se13/style.css
app/src/test/java/org/se13/view/controller/ControllerTest.java

#88 Pull Request에서 설정화면이 제대로 작동하지 않던 문제를 수정했습니다.

fix: 설정화면이 작동하지 않던 문제 수정

---

app/src/main/java/org/se13/game/block/Block.java
app/src/main/java/org/se13/game/block/BlockColor.java
app/src/main/java/org/se13/view/difficulty/LevelSelectScreenController.java
app/src/main/java/org/se13/view/tetris/BattleScreenController.java
app/src/main/java/org/se13/view/tetris/Player.java
app/src/main/java/org/se13/view/tetris/TetrisScreenController.java

#94 
Player class를 만들어서 player에서 TetrisAction, TetrisEvent, LocalTetrisServer, BattleTetrisSever 모두 관여할 수 있도록 만들었습니다. 
userID에 따라 configRepo를 각각 불러오는 작업이 이후에 필요할 것 같습니다.

feature: Player Class 구현

---

app/src/main/java/org/se13/SE13Application.java
app/src/main/java/org/se13/game/block/Block.java
app/src/main/java/org/se13/game/config/Config.java
app/src/main/java/org/se13/sqlite/config/ConfigRepository.java
app/src/main/java/org/se13/sqlite/config/ConfigRepositoryImpl.java
app/src/main/java/org/se13/sqlite/config/PlayerKeycode.java
app/src/main/java/org/se13/view/difficulty/LevelSelectScreenController.java
app/src/main/java/org/se13/view/setting/SettingScreenController.java
app/src/main/java/org/se13/view/tetris/BattleScreenController.java
app/src/main/java/org/se13/view/tetris/Player.java
app/src/test/java/org/se13/game/block/BlockColorTest.java
app/src/test/java/org/se13/sqlite/config/ConfigRepositoryImplTest.java

ConfigRepository 싱글톤 제거 및 PlayerKeyCode 추가

---

app/src/main/java/org/se13/online/OnlineActionRepository.java
app/src/main/java/org/se13/online/OnlineBattleTetrisServer.java
app/src/main/java/org/se13/online/OnlineEventPacket.java
app/src/main/java/org/se13/online/OnlineEventRepository.java

Issue: #91 
Object I/O Stream을 이용하여 직렬화를 진행하였습니다.

Object I/O Stream을 이용한 직렬화

---

app/src/main/java/org/se13/online/OnlineEventRepository.java
app/src/main/java/org/se13/online/ReadNetworkRepository.java
app/src/main/java/org/se13/online/TetrisServerSocket.java
app/src/main/java/org/se13/view/difficulty/LevelSelectScreenController.java
app/src/main/java/org/se13/view/start/StartScreenController.java
app/src/main/resources/org/se13/StartScreen.fxml

온라인 대전 모드 자잘한 수정
